services:
  db:
    image: postgres:15-alpine
    container_name: auction_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/  # Local directory instead
    ports:
      - "5433:5432"  # Changed from 5432:5432 to 5433:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: 
      context: ./front
      no_cache: true
    container_name: auction_frontend
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.vite
    ports:
      - "7500:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true 
      # Change these for local development:
      - VITE_API_URL=http://localhost:8451/api
      - VITE_WS_URL=ws://localhost:8451/ws
    restart: unless-stopped

  backend:
    build: 
      context: ./back
      no_cache: true
    container_name: auction_backend
    command: /entrypoint.sh
    volumes:
      - ./back:/app
    ports:
      - "8451:7500"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped

