services:
  db:
    image: postgres:15-alpine
    container_name: auction_db
    environment:
      - POSTGRES_DB=${DB_NAME:-auction}
      - POSTGRES_USER=${DB_USER:-ringo}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-@fric@9619}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-auction}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auction_network

  redis:
    image: redis:7-alpine
    container_name: auction_redis
    ports:
      - "6380:6379"  
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - auction_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: auction_backend
    command: /entrypoint.sh
    volumes:
      - ./back:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8451:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=redis://redis:6379/0
      # Fix API URL references
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,backend,auction_backend}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173,http://localhost:7500,http://127.0.0.1:7500}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - auction_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: auction_frontend
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.svelte-kit
      - /app/.vite
    ports:
      - "7500:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      # FIXED: WebSocket URL should match backend routing pattern
      - VITE_API_BASE_URL=http://localhost:8451/api
      - VITE_WS_BASE_URL=ws://localhost:8451/ws
    restart: unless-stopped
    networks:
      - auction_network
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  auction_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: