services:
  backend:
    build: 
      context: ./back
      no_cache: true
    container_name: auction_backend
    command: /entrypoint.sh
    volumes:
      - ./back:/app
    ports:
      - "7500:7500"
    env_file:
      - ./.env

  frontend:
    build: 
      context: ./front
      no_cache: true
    container_name: auction_frontend
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.vite  # Exclude Vite cache from host
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - VITE_API_URL=http://backend:7500/api
    depends_on:
      - backend



# we can introduce our postgres data her but it would be more safer with .env and it's   settings file
# volumes: # Uncomment and define if you add a database service
#   postgres_data:

# services: # Example for a PostgreSQL database service
#   db:
#     image: postgres:13
#     container_name: auction_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=your_db_user
#       - POSTGRES_PASSWORD=your_db_password
#       - POSTGRES_DB=your_db_name
#     ports:
#       - "5432:5432"