# Generated by Django 5.1.4 on 2025-02-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='base_catego_parent__08aa61_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='auction',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='factory_images/'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='factory_images/'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='factory_images/'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='factory_images/'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='factory_images/'),
        ),
        migrations.AddField(
            model_name='heavyvehicleauction',
            name='heavy_vehicle_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='heavy_vehicle_images/'),
        ),
        migrations.AddField(
            model_name='heavyvehicleauction',
            name='heavy_vehicle_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='heavy_vehicle_images/'),
        ),
        migrations.AddField(
            model_name='heavyvehicleauction',
            name='heavy_vehicle_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='heavy_vehicle_images/'),
        ),
        migrations.AddField(
            model_name='heavyvehicleauction',
            name='heavy_vehicle_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='heavy_vehicle_images/'),
        ),
        migrations.AddField(
            model_name='heavyvehicleauction',
            name='heavy_vehicle_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='heavy_vehicle_images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='machinery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='machinery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='machinery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='machinery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='machinery_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('REALESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('MACHINERY', 'Machinery'), ('FACTORY', 'Factory'), ('HEAVYVEHICLE', 'Heavy Vehicle')], max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='base.subcategory'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug'], name='base_subcat_slug_73d016_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='base_subcat_categor_82c3da_idx'),
        ),
    ]
