# Generated by Django 5.1.4 on 2025-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', to='accounts.role', verbose_name='roles'),
        ),
    ]
